### ISSUE TITLE
Multiple ECONNRESET error

### ISSUE THREAD

**Issue by ThauEx** [runk/node-thin#15]
I'm using this library to proxy an android app.
When using a browser its working fine, but when using the android app, I'm having a lot of ECONNRESET errors.

This is one of the traces I'm getting

```
Trace: < ERR (proxy socket): Error: read ECONNRESET
    at Socket.<anonymous> (MYPROJECT\node_modules\thin\lib\thin.js:130:13)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)
Trace: > ERR (socket request): Error: write after end
    at Socket.<anonymous> (MYPROJECT\node_modules\thin\lib\thin.js:135:13)
    at Socket.emit (events.js:129:20)
    at writeAfterEnd (_stream_writable.js:169:10)
    at Socket.Writable.write (_stream_writable.js:214:5)
    at Socket.write (net.js:634:40)
    at Socket.<anonymous> (MYPROJECT\node_modules\thin\lib\thin.js:129:19)
    at Socket.emit (events.js:107:17)
    at onwriteError (_stream_writable.js:317:10)
    at onwrite (_stream_writable.js:335:5)
    at WritableState.onwrite (_stream_writable.js:105:5)
    at fireErrorCallbacks (net.js:456:13)
    at Socket._destroy (net.js:467:5)
    at Socket._writeGeneric (net.js:656:10)
    at Socket._write (net.js:709:8)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
Trace: < ERR (proxy socket): Error: This socket is closed.
    at Socket.<anonymous> (MYPROJECT\node_modules\thin\lib\thin.js:130:13)
    at Socket.emit (events.js:107:17)
    at onwriteError (_stream_writable.js:317:10)
    at onwrite (_stream_writable.js:335:5)
    at WritableState.onwrite (_stream_writable.js:105:5)
    at fireErrorCallbacks (net.js:456:13)
    at Socket._destroy (net.js:467:5)
    at Socket._writeGeneric (net.js:656:10)
    at Socket._write (net.js:709:8)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Socket.Writable.write (_stream_writable.js:217:11)
    at Socket.write (net.js:634:40)
    at Socket.<anonymous> (MYPROJECT\node_modules\thin\lib\thin.js:120:17)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
Trace: > ERR (socket request): Error: write after end
    at Socket.<anonymous> (MYPROJECT\node_modules\thin\lib\thin.js:135:13)
    at Socket.emit (events.js:129:20)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)
```

Another one is:

```
Trace: > ERR (socket request): Error: read ECONNRESET
    at Socket.<anonymous> (MYPROJECT\node_modules\thin\lib\thin.js:135:13)
    at Socket.emit (events.js:129:20)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)
```

I don't get why and where this errors are commign from. When I activate the proxy after the "initial loading phase" of the app, its working fine.

EDIT: I added a few lines to thin.js, so it supports windows and uses a port instead of a socket.

**Comment by bls** [comment]
Do you know if the Android application is using websockets by any chance?

**Comment by ThauEx** [comment]
No, just GET and POST via HTTPS.

**Comment by bls** [comment]
Since you're HTTPS it is possible that the client is getting SSL certificate errors and disconnecting after the initial handshake. If you trace via Wireshark it should be possible to confirm this without decrypting the SSL traffic (you'll see a Hello and certificate exchange, then the client will end/reset the connection). 

If you can attach a wireshark trace I'm happy to take a look. If this is the case then it is possible to work around the problem by adding an SNICallback (as per examples) and installing a trusted root cert on the device.

**Comment by ThauEx** [comment]
I already have trusted root certificate and using the SNICallback. Like what I said, it is failing in the initial loading phase, after that it's working fine. Opening the (failing) urls in a browser works fine.
But I will try to provide a wireshark trace.

**Comment by bls** [comment]
Oh yup, sorry, I didn't read the loading part properly...  interesting.

**Comment by ThauEx** [comment]
Can I send you the file via mail? I don't want to make it public here :D

**Comment by bls** [comment]
Sure blair.strang+gh_issues@gmail.com

**Comment by kamilbiela** [comment]
hi, any news on that? I have similar issues: 
When using firefox + this lib as proxy, I'm also seeing lot of (both in http and https): 
```
> ERR: Error: write after end
< ERR: Error: This socket has been ended by the other party
> ERR: Error: write after end
```

very often I have when accessing https: 
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: 140735166313216:error:14094412:SSL routines:SSL3_READ_BYTES:sslv3 alert bad certificate:../deps/openssl/openssl/ssl/s3_pkt.c:1289:SSL alert number 42
```
it occurs when entering https://google.pl for example. Sometimes first request is ok, sometimes it fails. But I can see full page in browser.

**Comment by ThauEx** [comment]
Are you using the SNI callback?
If so: I modified thin.js to support the default ssl cert+key from options instead of hardcoded ones and now it seems to work. I still have some smaller issues, but no idea, if this is related to thin.

**Comment by kamilbiela** [comment]
```
var proxy = new Thin({
    followRedirect: false,
    strictSSL: false,
    rejectUnauthorized: false
});```
I'm also using node version v0.11.13 (I plan to use this lib with electron.io)

**Comment by bls** [comment]
@kamilbiela @ThauEx - A bit of an update. So initially I thought this might be certificate pinning, but in @ThauEx's case, it was that the client was issuing some requests without SNI, which meant that the SNICallback never got called. This meant that the proxy was sending the default "Internet Widgits" certificate back for the site instead of a generated cert (or even the right custom root).

Working connections had the server_name extension in the "Client Hello" SSL packet, and looked like:

![image](https://cloud.githubusercontent.com/assets/203738/8597161/13820002-2697-11e5-86d6-c174b7f685d0.png)

Connections that failed did not have this. My conclusion is that the non-working calls did not have SNI support because they were issued from Android libraries which somehow did not use SNI (in this case, from diagnostics and telemetry code in the application, not the "application" itself). Everything was TLS v1.2.

However, none of this should not be a problem if you are using Firefox. That is, Firefox should use SNI without exception. Alert 42 definitely means that the client rejected the SSL certificate presented by the server (or in this case, was generated by the proxy). 

Diagnostic steps:

* Ensure that your CA certificate is loaded into Firefox (guessing you have this!)
* I'm not sure if async SNICallback works in 0.11.13; it did work in 0.12 for me, but not 0.10. I guess easiest thing is to print-debug this and verify certs are being generated.
* Check security.cert_pinning.enforcement_level = 1 in about:config in firefox (the default, which allows MITM via user root certs).

**Comment by bls** [comment]
I tested and can confirm that SNICallback does not work in 0.11.3. This means that you can accept the untrusted certificate for the site in FF, but lots of page requisites won't load properly (e.g. CSS, images) because they come other domains, for which the cert isn't approved yet.

As far as I know, if you want "proper" SNI support, you need node v0.12.

**Comment by bls** [comment]
OK, if SNICallback is not enabled at all (as per updated code above), then the proxy can only return a fixed SSL cert and you will tend to get these warnings if the client validates certificates.

**Comment by kamilbiela** [comment]
0.11.3 or 0.11.13? I think it works 0.11.13 and makes things a lot better, but still from time to time I have err connection on i.e. https://pinterest.com

Also noticed that only first request to https://www.facebook.com/?_rdr=p is returned always without background images. if I F5 then all images shows up.

**Comment by kamilbiela** [comment]
Hmm... maybe thats something broken in node 0.11.13? I just got segfault

Generating new TLS certificate for: safebrowsing.google.com
Generating new TLS certificate for: self-repair.mozilla.org
> ERR: Error: read ECONNRESET
Generating new TLS certificate for: pixel.facebook.com
Segmentation fault: 11

**Comment by bls** [comment]
Ah, tried again with 0.11.13 and I got a crash too. Looking at: https://nodejs.org/docs/v0.11.13/api/ it looks like it _should_ support async SNI (it seems it became async in 0.11.5)....
